### PR TITLE
Added promptText property to JFXChipView

### PR DESCRIPTION
**Pull request by DropSnorz**
Hi ! I've added a simple property on JFXChipView to fill the associated TextArea promptText. 🙂 
You can use it like this: `chipView.setPromptText("Some placeholder");`

### CODE REVIEW

**Comment by jfoenixadmin** [comment]
Hello @DropSnorz 
It's good to have a prompt text property in JFXChipView. However, we still need to handle label float property (as in JFXTextFields / JFXTextArea). A simple prompt text is not enough.

**Comment by DropSnorz** [comment]
Thank you. Prompt texts are not part of the [Chips Material Design Specification](https://material.io/design/components/chips.html#). I can try to implement the same floating behaviour than JFXTextArea / JFXTextField.

**Comment by DropSnorz** [comment]
Hm... In fact my goal is more to set a prompt text to the inner TextArea rather than a real text placeholder on the component. 
jfoenix-chips
If you think this behaviour is relevant for Material Design, i can rename the property `innerPromptText` ?

**Comment by jfoenixadmin** [comment]
I see, let's add it as is for now. Maybe we can update the skin later on to support label float or some other design. I have 1 comment before merging, can you remove the prompt text listener and bind prompt text properties instead? (simpler code)

**Comment by DropSnorz** [comment]
Thank you for the review. Everything should be ok now 🙂

**Comment by jfoenixadmin** [comment]
Thanks @DropSnorz  for the PR 👍

**Pull request merged**
