### PR TITLE
Add forgoten updateAnimation()

### PR DESCRIPTION
**Pull request by Djaler**
Cause it fail in playAnimation() without this

### CODE REVIEW

**Comment by Djaler** [comment]
So what abot this, guys?

**Comment by jfoenixadmin** [comment]
Hello, well updateAnimation method shouldn't be called when selection is change.
Can you provide a sample demo for this issue?

Regards,

**Comment by Djaler** [comment]
@jfoenixadmin look at gist https://gist.github.com/Djaler/6e2d44b321ef7d2882b6f828196a8cc2.

**Comment by Djaler** [comment]
And stacktrace 
```Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.jfoenix.skins.JFXRadioButtonSkin.playAnimation(JFXRadioButtonSkin.java:190)
	at com.jfoenix.skins.JFXRadioButtonSkin.handleControlPropertyChanged(JFXRadioButtonSkin.java:142)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase.lambda$registerChangeListener$61(BehaviorSkinBase.java:197)
	at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.scene.control.ToggleButton.setSelected(ToggleButton.java:149)
	at demos.components.TreeTableDemo$ButtonsTableCell.updateItem(TreeTableDemo.java:98)
	at demos.components.TreeTableDemo$ButtonsTableCell.updateItem(TreeTableDemo.java:73)
	at javafx.scene.control.TreeTableCell.updateItem(TreeTableCell.java:655)
	at javafx.scene.control.TreeTableCell.indexChanged(TreeTableCell.java:457)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:533)
	at com.sun.javafx.scene.control.skin.TreeTableRowSkin.updateCells(TreeTableRowSkin.java:220)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.init(TableRowSkinBase.java:147)
	at com.sun.javafx.scene.control.skin.TreeTableRowSkin.<init>(TreeTableRowSkin.java:89)
	at com.jfoenix.skins.JFXTreeTableRowSkin.<init>(JFXTreeTableRowSkin.java:59)
	at com.jfoenix.controls.JFXTreeTableRow.createDefaultSkin(JFXTreeTableRow.java:45)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Node.applyCss(Node.java:9155)
	at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1964)
	at com.sun.javafx.scene.control.skin.VirtualFlow.addLeadingCells(VirtualFlow.java:1246)
	at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1194)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene.preferredSize(Scene.java:1646)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:846)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at demos.components.TreeTableDemo.start(TreeTableDemo.java:56)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by jfoenixadmin** [comment]
Thanks for pointing out the issue 👍 , however the updateAnimation method should only be called if the timline is null, otherwise no need to call it.

**Comment by jfoenixadmin** [comment]
The fix is included in JFoenix 1.6

Regards,

**Pull request closed without merging**
