### PR TITLE
JFXPasswordField add password entry box to display in clear text

### PR DESCRIPTION
**Pull request by yousiqi**
The default JFXPasswordField  cannot see the clear text, and the accuracy of password input cannot be verified. In the modification, the clear text display of password is added and the functions of copying and cutting are supported

GIF

### CODE REVIEW

**Review by jfoenixadmin — CHANGES_REQUESTED** [review]
Hello,
I reviewed your code, I think it needs some changes before merging:

1. maskTextProperty doesn't have a setter method, it's only settable using the property.
2. maskTextProperty should trigger pseudo class changes
2. DEFAULT_COLOR StyleableObjectProperty is not needed, you can set the color/content/size of SVGGlyph using CSS
4. reverseEye method should be implemented by toggling pseudo classes/css instead.
 - only 1 class is needed HAS_RIGHT_NODE or HAS_NO_SIDE_NODE, there is no point of having 2 classes.
5. All default css styling can be applied in getUserAgentStylesheet
6. There is no registered listener for "RIGHT_NODE", it's never true in handleControlPropertyChanged

All in all, I think the code is not complete yet.
Regards,

**Review by jfoenixadmin — CHANGES_REQUESTED** [review]
It's getting better :), however still needs some changes:

1. you can replace PSEUDO_CLASS_OPEN, PSEUDO_CLASS_CLOSE  with 1 pseudo class, lets call it PSEUDO_MASKED
2. it's better to apply the PSEUDO_MASKED on the control (which is the passwordfield), instead of applying it to the icon.
3. it's better to rename the property "mask" to "maskedText", and rename the getter to is***() instead of get***() since it's a boolean property.

We are getting there :), nice work 👍 
Regards,

**Comment by yousiqi** [comment]
thanks for your advice, please check the latest modified code, I think it is very good @jfoenixadmin

**Comment by jfoenixadmin** [comment]
I was reviewing MD [TextField ](https://material.io/components/text-fields) component, it has leading/trailing icons.
I think that would be a better implementation as it's more flexible, I also noticed that the icon is part of the text field (the text field line goes under the icon too, unlike your skin implementation). All in all, we need add 2 node properties for those icons inside the control and update the skin implementation (leading/trailing icons can be part of JFXTextFieldSkin, no need to create a custom skin for password field). Thus at the moment, I can only merge the JFXPasswordField.java changes from your PR. 

Your PR is appreciated, thank you.

**Comment by jfoenixadmin** [comment]
Hello, I just pushed bbb653aa222177576ebb8d034adf7b779d832e06. This change allows the user to do the following:
1. Set leading/trailing graphics for JFXTextField/JFXPassword
2. JFXPassword has a maskedText property, updating its value will toggle the password mask and the pseudo class "unmasked".

Regards,

**Pull request closed without merging**
