### PR TITLE
Updates to use JavaFX 11 and module system

### PR DESCRIPTION
**Pull request by ronymesquita**
The updates was made to use **JavaFX 11** and **module system**, changing versions of Gradle plugins, adding new command-line arguments to compile the code and the switch to Gradle 5.6.3.
Inside the changes, was used the plugin [org.openjfx.javafxplugin](https://plugins.gradle.org/plugin/org.openjfx.javafxplugin) to get JavaFX from Maven repository, instead of local installation.
The [demo](https://github.com/jfoenixadmin/JFoenix/tree/JFoenix-9.0.0/demo) not worked in my tests because [DataFX](https://github.com/guigarage/DataFX) is blocked by the module system and can not load FXML files from other modules. The attempts to run this project always have NullPointerException to load Main.fxml on MainController and the same problem with other FXML files.

### CODE REVIEW

**Comment by acaproni** [comment]
Is there any plan to merge or port jfoenix to jdk 11? There are many open issues on this topic...

**Comment by axel1200** [comment]
This lib really needs support for newer java and java fx versions, otherwise dropping becomes the only option :(

**Comment by objectProgrammer** [comment]
@axel1200 I'm using Java 13 + JavaFX 13 + Java Modules + Gradle 6.0.1 + JFoenix 9.0.8 without a single problem, this pull request is not needed at all. I've only used the JFXSlider so I cannot tell for sure if it works fully on Java 11+ but I haven't experienced any problems.

**Comment by ronymesquita** [comment]
> @axel1200 I'm using Java 13 + JavaFX 13 + Java Modules + Gradle 6.0.1 + JFoenix 9.0.8 without a single problem, this pull request is not needed at all. I've only used the JFXSlider so I cannot tell for sure if it works fully on Java 11+ but I haven't experienced any problems.

Probably Gradle 6 helped to resolve the problem with compatibility, because the pull request was made with Gradle 5. This Gradle [guide](https://guides.gradle.org/building-java-9-modules/) says that Gradle 6 is compatible with module system and problably this pull request request is not more needed.

**Comment by objectProgrammer** [comment]
Parts of this should probably be merged as it updated the demo to work with Java 11+

**Comment by ronymesquita** [comment]
👍

**Pull request closed without merging**
