### PR TITLE
Fixed demo sizing issue & updated readme

### PR DESCRIPTION
**Pull request by rfenters95**
Running the demo on a mac book pro 13' opens a window that exceeds the limits of the screen. Additionally, the window is unable to be resized because of the fixed minimum dimensions. As you can see below.

pre-update

I removed the fixed minimum dimensions, so that the resulting smaller window can be maximized to the individual's screen. 

post-update

Finally, I updated the README to include the specific path and file names to the JAR generated via Gradle.

### CODE REVIEW

**Comment by rfenters95** [comment]
Sorry about that last commit "Update LICENSE", adding the license to the top of the repo required Github's latest version. However, upon reading the changes I believe you were suppose to fill out the part `Copyright {yyyy} {name of copyright owner}` with your information. Example `Copyright 2014 JFoenix`.

**Comment by jfoenixadmin** [comment]
Hello, 
yeah you are right, we need to fill these in the LICENSE file. Thanks for pointing out the issue 👍.

One more thing before accepting the pull request, its better to have initial scene size related to the screen size instead of passing the root only. if you can do that it would be appreciated.

Regards,

**Comment by rfenters95** [comment]
No problem, happy to help. I added the initial scene size, as requested. Below is an image of how it looks on 13-inch screens.

upload

One thing I did notice when making this change is that if setMaximized(true) were included, then then the stage should open nicely regardless of the individual's screen size. However, it appears that there is a custom maximize function consuming this call. I can look into this later if you wish.

**Comment by jfoenixadmin** [comment]
well, we implemented a custom maximize function as part of the window is being hidden under the operating system task bar. it's fine no need to look into it.

Thanks for the pull request 👍

**Comment by rfenters95** [comment]
Sorry, I did not know what you referring to regarding the scene size. I am still fairly new to JavaFX.

**Comment by jfoenixadmin** [comment]
It's fine, looking forward for more PRs :). 

Regards,

**Pull request merged**
