### PR TITLE
Fixed #75 JFXTabPane no tab closing button

### LINKED ISSUE #75: JFXTabPane no tab closing button
What I really miss and I cant get it to work is a closing button on a Tab in the JFXTabPane.
Is this a known issue or is there a work around?

### PR DESCRIPTION
**Pull request by Enigo**
"Close button" added
plus minor fixes

TabClosingPolicy.ALL_TABS

TabClosingPolicy.SELECTED_TAB

TabClosingPolicy.UNAVAILABLE

### CODE REVIEW

**Comment by Enigo** [comment]
The only question I have : is this simple 'x' mnemonic good enough? :)

**Comment by jfoenixadmin** [comment]
Hi, 
Thanks for your contribution 👍 
regarding the close button, we are looking for some material design behavior like to implement instead of adding a simple close button.

Regards, and thanks for your contribution

**Comment by Enigo** [comment]
Yeah, that would be great! Never saw material design behaviour for tabs closing though. Couldn't google it either)
So, shall I close this then?

**Comment by Enigo** [comment]
By 
> I updated the jfoenix jar

you mean that you downloaded source code, applied my change and built the jar or just downloaded the jar as-is? if the later then you would not find my change there since commit is not pushed.
Otherwise `tabPane.setTabClosingPolicy(TabClosingPolicy.ALL_TABS);` should work.

**Comment by goxr3plus** [comment]
Wow i was waiting for this :)

**Comment by goxr3plus** [comment]
When this feature will be implemented i can't wait anymore please add it !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jfoenixadmin** [comment]
Hello, 
JFXTabPane now supports close all tabs policy. However selected tab policy is not supported, it could be implemented by adding a close button inside the tab content instead of the tabs header.

Regards,

**Pull request closed without merging**
