### PR TITLE
Gradle build

### PR DESCRIPTION
**Pull request by aalmiray**
This pull request proposes the following changes

 * Migrate build to multi project Gradle structure
 * Apply license headers to all files

Tried to keep the original structure but it was easier to relocate all source files to their expected locations. Apply any of the following commands to build and run the projects

 * gradle jar. Creates all artifact jars.
 * gradle build. Builds all artifacts, checks all source files.
 * gradle run. Runs the main demo.
 * gradle bintrayUpload. Uploads a new version to bintray.com
 * gradle licenseFormat. Applies formatting to license headers

These new settings allow the project to be published on bintray.com, simply put: Github for binaries.

### CODE REVIEW

**Comment by spyhunter99** [comment]
no love for maven?

**Comment by aalmiray** [comment]
After spending 7 years with Maven and 5 more with Gradle I cans say with good confidence that Gradle is the superior build tool. Besides migrating from Ant to Gradle is easier than from Ant to Maven.

**Comment by jfoenixadmin** [comment]
thanks its very appreciated, however we want to keep the ant build files. if you can pull the latest changes and just add Gradle build files it would be great. Thanks again

**Comment by aalmiray** [comment]
Sure, no problem. Would it be OK to relocate classes to follow the Maven/Gradle conventions? Now that I know more about the layout and how the sources work I could also keep the old one if you like.

**Comment by aalmiray** [comment]
I'll close this PR and send a different one

**Pull request closed without merging**
