### PR TITLE
Support tooltips for non-controls in ValidatorBase and add documentation

### PR DESCRIPTION
**Pull request by TurekBot**
In PR #1013, I did this same fix, but on an old version of `ValidatorBase`. This applies that same fix to the most recent version, instead.

While I was at it, I also added documentation for almost everything in `ValidatorBase`. Feel free to check my work, as I'm not the original author of the class—what I wrote is based on assumptions.

### CODE REVIEW

**Comment by skmedix** [comment]
I'll try to review this asap

**Comment by jfoenixadmin** [comment]
Hi @TurekBot, It looks fine to me. But I think we should also support JFXTooltip, so we might need to use a different approach. btw the documentation looks great :) 👍

**Comment by jfoenixadmin** [comment]
@TurekBot, maybe we should update the existing tooltip text instead of creating a new one. Or provide a tooltip supplier for the validator base. Or Both  (still thinking about it...)

**Comment by jfoenixadmin** [comment]
@TurekBot , I was reviewing ValidatorBase class, and I noticed it extends Parent class. which doesn't make sense (not sure what was I thinking back then :s). So I think we need to update ValidatorBase so support the following:

1. Multiple source controls, so the validator itself is reusable for different nodes (so we need to keep track of multiple saved tooltips in a map where the key is the source control itself).
2. Custom tooltips (I think by providing a callback or a function that takes the error msg as an argument and returns the tooltip would be a good impl)
3. Support JFXTooltip

For now, I'll accept the PR then update ValidatorBase to support these features.
what do you think @TurekBot?

**Comment by jfoenixadmin** [comment]
@TurekBot I agree, it should be of type node.

**Pull request merged**
