### PR TITLE
Build: update Gradle, refactor build.gradles

### PR DESCRIPTION
**Pull request by thetric**
This is a rather huge PR:

* update Gradle wrapper (2.3 -> 3.4.1)
* update Gradle plugins
* refactor `build.gradle` files
* enable incremental compilation for better build performance
* use FontAwesome and other deps from the Maven repo instead of the `libs` dir (in `demo` project)

### CODE REVIEW

**Comment by jfoenixadmin** [comment]
Hello, 
Thanks for your contribution to JFoenix, please note that updating to the latest Font Awesome will break the FXML code too not just the java files. Can't merge the pull request just yet.

Regards,

**Comment by thetric** [comment]
@jfoenixadmin I have updated the PR with two more commits that fix the demo app

**Comment by jfoenixadmin** [comment]
Hello, 
Thanks for the fix 👍 , however the icons in the demo are not showing properly, they are being replaced with a black box instead of the actual icon. if you can fix the issue before merging with master branch it would be appreciated.

Regards,

**Comment by thetric** [comment]
Hm, I haven't noticed any problems in the demo. Which parts contained broken icons?

**Comment by jfoenixadmin** [comment]
Icons, listview and combobox demo

**Comment by jfoenixadmin** [comment]
Thanks for your great contribution to JFoenix 👍

**Comment by thetric** [comment]
The last commit has fixed the color issue, but the badges aren't still displayed correctly :(

**Comment by jfoenixadmin** [comment]
It's ok, the issue is fixed and pushed to github.

**Pull request merged**
